# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cedc59ca558c0422d71800b11c0ee7bd324c11fdfca4e42822af7d28f076828326be7de710e5344014e19bd9ad9b6e474d641cd98ceb7d38d5250f4f0c2de14

test:
  secret_key_base: feae0569dd13cf6221c8e17ea89dfb5135d39a9d2747996571b04a3434c794ae1133bc954821c32feeee9e94f62f3d791cb48a2dff5f10a5009016da9a1f7de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
